; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino

src_filter = +<src/main.cpp>

; =============================
;  2. PCネイティブシミュレーション環境
; =============================
[env:native_sim]
platform = native
lib_deps = 
	lvgl/lvgl@~8.3.11
    lvgl/lv_drivers@~8.3.0
build_flags = 
	-D LV_DRIVERS_USE_SDL=1
	-D LV_USE_SDL=1

	; lv_driversが "lv_drv_conf.h" を "lv_conf.h" を見つけるため
    -D LV_CONF_INCLUDE_SIMPLE
    -I include

	; 以下2行を追加: lv_drivers が lvgl.h を見つけるため
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I $PROJECT_LIBDEPS_DIR/$PIOENV/lvgl/src

    -I src
    -I src/hal
    -I src/ui



    ; MSYS2のincludeパス (SDL.h のために必要)
	-I C:/msys64/mingw64/include/SDL2

    ; <sdl/lv_port_sdl.h> を見つけるため
    -I $PROJECT_LIBDEPS_DIR/$PIOENV/lv_drivers
    
    -I $PROJECT_DIR/include
    
    ; リンカパス (L) - ライブラリを探す場所
    -L C:/msys64/mingw64/lib

    ; -I deps/sdl2/include ; Include path for SDL2
	; -L deps/sdl2/lib ; Linker flags for SDL2
    ; MSYS2でインストールしたSDL2ライブラリとリンクする
    -lmingw32
    -lSDL2main
	-lSDL2
    -lSDL2_ttf
