// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#ifndef UI_ANALYTICSSCREEN_H
#define UI_ANALYTICSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AnalyticsScreen
extern void ui_AnalyticsScreen_screen_init(void);
extern void ui_AnalyticsScreen_screen_destroy(void);
extern lv_obj_t * ui_AnalyticsScreen;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

