// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#include "ui.h"

lv_obj_t * ui_DebugScreen = NULL;
lv_obj_t * ui_debugmonitor = NULL;
lv_obj_t * ui_Switch2 = NULL;
// event funtions
void ui_event_debugmonitor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_OVER_RIGHT, 200, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_DebugScreen_screen_init(void)
{
    ui_DebugScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DebugScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_debugmonitor = lv_textarea_create(ui_DebugScreen);
    lv_obj_set_width(ui_debugmonitor, 320);
    lv_obj_set_height(ui_debugmonitor, 240);
    lv_obj_set_align(ui_debugmonitor, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_debugmonitor, "Placeholder...");
    lv_obj_clear_flag(ui_debugmonitor, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_Switch2 = lv_switch_create(ui_DebugScreen);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, -287);
    lv_obj_set_y(ui_Switch2, 63);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_debugmonitor, ui_event_debugmonitor, LV_EVENT_ALL, NULL);

}

void ui_DebugScreen_screen_destroy(void)
{
    if(ui_DebugScreen) lv_obj_del(ui_DebugScreen);

    // NULL screen variables
    ui_DebugScreen = NULL;
    ui_debugmonitor = NULL;
    ui_Switch2 = NULL;

}
