// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#ifndef UI_DEBUGSCREEN_H
#define UI_DEBUGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DebugScreen
extern void ui_DebugScreen_screen_init(void);
extern void ui_DebugScreen_screen_destroy(void);
extern lv_obj_t * ui_DebugScreen;
extern void ui_event_debugmonitor(lv_event_t * e);
extern lv_obj_t * ui_debugmonitor;
extern lv_obj_t * ui_Switch2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

