// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#include "ui.h"

lv_obj_t * ui_GraphScreen = NULL;
lv_obj_t * ui_Chart1 = NULL;
// event funtions

// build funtions

void ui_GraphScreen_screen_init(void)
{
    ui_GraphScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GraphScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_GraphScreen);
    lv_obj_set_width(ui_Chart1, 260);
    lv_obj_set_height(ui_Chart1, 196);
    lv_obj_set_x(ui_Chart1, 15);
    lv_obj_set_y(ui_Chart1, -12);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

}

void ui_GraphScreen_screen_destroy(void)
{
    if(ui_GraphScreen) lv_obj_del(ui_GraphScreen);

    // NULL screen variables
    ui_GraphScreen = NULL;
    ui_Chart1 = NULL;

}
