// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#ifndef UI_GRAPHSCREEN_H
#define UI_GRAPHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GraphScreen
extern void ui_GraphScreen_screen_init(void);
extern void ui_GraphScreen_screen_destroy(void);
extern lv_obj_t * ui_GraphScreen;
extern lv_obj_t * ui_Chart1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

