// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#include "ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_serialraw = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_analytics = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_loglist = NULL;
lv_obj_t * ui_setting = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_setting1 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_serialraw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RawScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_RawScreen_screen_init);
    }
}

void ui_event_analytics(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AnalyticsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_AnalyticsScreen_screen_init);
    }
}

void ui_event_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_SettingScreen_screen_init);
    }
}

void ui_event_setting1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DebugScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_DebugScreen_screen_init);
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_serialraw = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_serialraw, 70);
    lv_obj_set_height(ui_serialraw, 50);
    lv_obj_set_x(ui_serialraw, 120);
    lv_obj_set_y(ui_serialraw, -90);
    lv_obj_set_align(ui_serialraw, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_serialraw, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_serialraw, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_serialraw);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Raw");

    ui_analytics = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_analytics, 70);
    lv_obj_set_height(ui_analytics, 50);
    lv_obj_set_x(ui_analytics, 120);
    lv_obj_set_y(ui_analytics, -30);
    lv_obj_set_align(ui_analytics, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_analytics, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_analytics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_analytics);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Analytics");

    ui_loglist = lv_roller_create(ui_HomeScreen);
    lv_roller_set_options(ui_loglist, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_loglist, 215);
    lv_obj_set_height(ui_loglist, 214);
    lv_obj_set_x(ui_loglist, -40);
    lv_obj_set_y(ui_loglist, 0);
    lv_obj_set_align(ui_loglist, LV_ALIGN_CENTER);

    ui_setting = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_setting, 70);
    lv_obj_set_height(ui_setting, 50);
    lv_obj_set_x(ui_setting, 120);
    lv_obj_set_y(ui_setting, 30);
    lv_obj_set_align(ui_setting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_setting);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Setting");

    ui_setting1 = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_setting1, 70);
    lv_obj_set_height(ui_setting1, 50);
    lv_obj_set_x(ui_setting1, 120);
    lv_obj_set_y(ui_setting1, 85);
    lv_obj_set_align(ui_setting1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setting1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setting1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_setting1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "debugg");

    lv_obj_add_event_cb(ui_serialraw, ui_event_serialraw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_analytics, ui_event_analytics, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setting1, ui_event_setting1, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_serialraw = NULL;
    ui_Label3 = NULL;
    ui_analytics = NULL;
    ui_Label2 = NULL;
    ui_loglist = NULL;
    ui_setting = NULL;
    ui_Label4 = NULL;
    ui_setting1 = NULL;
    ui_Label6 = NULL;

}
