// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern void ui_event_serialraw(lv_event_t * e);
extern lv_obj_t * ui_serialraw;
extern lv_obj_t * ui_Label3;
extern void ui_event_analytics(lv_event_t * e);
extern lv_obj_t * ui_analytics;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_loglist;
extern void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Label4;
extern void ui_event_setting1(lv_event_t * e);
extern lv_obj_t * ui_setting1;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

