// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#ifndef UI_RAWSCREEN_H
#define UI_RAWSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RawScreen
extern void ui_RawScreen_screen_init(void);
extern void ui_RawScreen_screen_destroy(void);
extern lv_obj_t * ui_RawScreen;
extern void ui_event_SerialPloter(lv_event_t * e);
extern lv_obj_t * ui_SerialPloter;
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

