// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: alcedo_debugger

#include "ui.h"

lv_obj_t * ui_RawScreen = NULL;
lv_obj_t * ui_SerialPloter = NULL;
lv_obj_t * ui_Switch1 = NULL;
// event funtions
void ui_event_SerialPloter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_OVER_RIGHT, 200, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_RawScreen_screen_init(void)
{
    ui_RawScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RawScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SerialPloter = lv_textarea_create(ui_RawScreen);
    lv_obj_set_width(ui_SerialPloter, 320);
    lv_obj_set_height(ui_SerialPloter, 240);
    lv_obj_set_align(ui_SerialPloter, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SerialPloter, "Placeholder...");
    lv_obj_clear_flag(ui_SerialPloter, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_RawScreen);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -287);
    lv_obj_set_y(ui_Switch1, 63);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_SerialPloter, ui_event_SerialPloter, LV_EVENT_ALL, NULL);

}

void ui_RawScreen_screen_destroy(void)
{
    if(ui_RawScreen) lv_obj_del(ui_RawScreen);

    // NULL screen variables
    ui_RawScreen = NULL;
    ui_SerialPloter = NULL;
    ui_Switch1 = NULL;

}
