; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; =============================
;  1. マイコンボード： Adafruit Feather ESP32-S3
; =============================
[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
board_build.flash_size = 16MB
board_build.partitions = default_16mb.csv
board_upload.flash_size = 16MB
board_upload.partitions = default_16mb.csv
framework = arduino
lib_deps = 
	lovyan03/LovyanGFX@~1.2.0
	; bblanchon/ArduinoJson@~7.4.2
	lvgl/lvgl@~8.3.4
	lewisxhe/SensorLib@^0.3.3 ; IMU用
build_flags = 
	-I include
monitor_speed = 115200

; =============================
;  2. PCネイティブシミュレーション環境
; =============================
[env:native_sim]
platform = native
lib_deps = 
	lvgl/lvgl@~8.3.11
    lvgl/lv_drivers@~8.3.0
build_flags = 
	-D LV_DRIVERS_USE_SDL=1
	-D LV_USE_SDL=1

	; lv_driversが "lv_drv_conf.h" を "lv_conf.h" を見つけるため
    -D LV_CONF_INCLUDE_SIMPLE
    -I include

	; 以下2行を追加: lv_drivers が lvgl.h を見つけるため
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I $PROJECT_LIBDEPS_DIR/$PIOENV/lvgl/src

    -I src
    -I src/hal
    -I src/ui

	; -I deps/sdl2/include ; Include path for SDL2
	; -L deps/sdl2/lib ; Linker flags for SDL2
	-lSDL2main
	-lSDL2
	-I C:/msys64/mingw64/include/SDL2

    ; main.cpp が <sdl/lv_port_sdl.h> を見つけるため
    -I $PROJECT_LIBDEPS_DIR/$PIOENV/lv_drivers/src
    
    -I $PROJECT_DIR/include