// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#ifndef _ALCEDO_PEBBLE_GUI_UI_H
#define _ALCEDO_PEBBLE_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_QrScreen.h"
#include "ui_SettingsScreen.h"
#include "ui_HomeScreen.h"
#include "ui_SkipScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_twitter_qr_png);    // assets/Twitter_QR.png
LV_IMG_DECLARE(ui_img_275677306);    // assets/River Scene - Morning_2x1.png
LV_IMG_DECLARE(ui_img_char_touched_png);    // assets/char_touched.png
LV_IMG_DECLARE(ui_img_char_idle_png);    // assets/char_idle.png
LV_IMG_DECLARE(ui_img_qr3_png);    // assets/qr3.png
LV_IMG_DECLARE(ui_img_larger_stone_icon_png);    // assets/Larger Stone Icon.png
LV_IMG_DECLARE(ui_img_setting2_png);    // assets/setting2.png
LV_IMG_DECLARE(
    ui_img_gemini_generated_image_c210npc210npc210_png);    // assets/Gemini_Generated_Image_c210npc210npc210.png
LV_IMG_DECLARE(ui_img_palet_stream_scene_sq_png);    // assets/Palet Stream Scene_sq.png
LV_IMG_DECLARE(ui_img_918493358);    // assets/Gemini_Generated_Image_5p46595p46595p46 (カスタム).png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
