// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#include "ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_ScrollContainer = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_PageMain = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_CharacterImage = NULL;
lv_obj_t * ui_NotificationIcon = NULL;
lv_obj_t * ui_MainBatteryLabel = NULL;
lv_obj_t * ui_WeatherIcon = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_PageMenu = NULL;
lv_obj_t * ui_PebbleIconQR = NULL;
lv_obj_t * ui_PebbleIconPebbleSkip = NULL;
lv_obj_t * ui_PebbleIconSettings = NULL;
lv_obj_t * ui_PebbleIconSafeCracker = NULL;
// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScrollContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_ScrollContainer);
    lv_obj_set_width(ui_ScrollContainer, 240);
    lv_obj_set_height(ui_ScrollContainer, 240);
    lv_obj_set_align(ui_ScrollContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScrollContainer, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_ScrollContainer,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ScrollContainer, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_ScrollContainer, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(ui_ScrollContainer, LV_SCROLL_SNAP_START);

    ui_Image2 = lv_img_create(ui_ScrollContainer);
    lv_img_set_src(ui_Image2, &ui_img_275677306);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 120);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PageMain = lv_obj_create(ui_ScrollContainer);
    lv_obj_set_width(ui_PageMain, 240);
    lv_obj_set_height(ui_PageMain, 240);
    lv_obj_set_align(ui_PageMain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PageMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PageMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PageMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PageMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_PageMain);
    lv_img_set_src(ui_Image1, &ui_img_char_touched_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 110
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_Image1, 31);
    lv_obj_set_y(ui_Image1, 41);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CharacterImage = lv_img_create(ui_PageMain);
    lv_img_set_src(ui_CharacterImage, &ui_img_char_idle_png);
    lv_obj_set_width(ui_CharacterImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharacterImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharacterImage, 22);
    lv_obj_set_y(ui_CharacterImage, 68);
    lv_obj_set_align(ui_CharacterImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CharacterImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CharacterImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NotificationIcon = lv_img_create(ui_PageMain);
    lv_obj_set_width(ui_NotificationIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NotificationIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NotificationIcon, -17);
    lv_obj_set_y(ui_NotificationIcon, -7);
    lv_obj_set_align(ui_NotificationIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NotificationIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NotificationIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NotificationIcon, 25);

    ui_MainBatteryLabel = lv_label_create(ui_PageMain);
    lv_obj_set_width(ui_MainBatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainBatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainBatteryLabel, -58);
    lv_obj_set_y(ui_MainBatteryLabel, 17);
    lv_obj_set_align(ui_MainBatteryLabel, LV_ALIGN_CENTER);

    ui_WeatherIcon = lv_img_create(ui_PageMain);
    lv_obj_set_width(ui_WeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherIcon, -66);
    lv_obj_set_y(ui_WeatherIcon, 3);
    lv_obj_set_align(ui_WeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WeatherIcon, 100);

    ui_TimeLabel = lv_label_create(ui_PageMain);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, -51);
    lv_obj_set_y(ui_TimeLabel, -11);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);

    ui_PageMenu = lv_obj_create(ui_ScrollContainer);
    lv_obj_set_width(ui_PageMenu, 240);
    lv_obj_set_height(ui_PageMenu, 240);
    lv_obj_set_x(ui_PageMenu, 0);
    lv_obj_set_y(ui_PageMenu, 240);
    lv_obj_set_align(ui_PageMenu, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PageMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PageMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PageMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PageMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PebbleIconQR = lv_img_create(ui_PageMenu);
    lv_img_set_src(ui_PebbleIconQR, &ui_img_qr3_png);
    lv_obj_set_width(ui_PebbleIconQR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PebbleIconQR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PebbleIconQR, -70);
    lv_obj_set_y(ui_PebbleIconQR, -25);
    lv_obj_set_align(ui_PebbleIconQR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PebbleIconQR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PebbleIconQR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PebbleIconPebbleSkip = lv_img_create(ui_PageMenu);
    lv_img_set_src(ui_PebbleIconPebbleSkip, &ui_img_larger_stone_icon_png);
    lv_obj_set_width(ui_PebbleIconPebbleSkip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PebbleIconPebbleSkip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PebbleIconPebbleSkip, 18);
    lv_obj_set_y(ui_PebbleIconPebbleSkip, -32);
    lv_obj_set_align(ui_PebbleIconPebbleSkip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PebbleIconPebbleSkip, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PebbleIconPebbleSkip, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PebbleIconSettings = lv_img_create(ui_PageMenu);
    lv_img_set_src(ui_PebbleIconSettings, &ui_img_setting2_png);
    lv_obj_set_width(ui_PebbleIconSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PebbleIconSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PebbleIconSettings, 19);
    lv_obj_set_y(ui_PebbleIconSettings, 51);
    lv_obj_set_align(ui_PebbleIconSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PebbleIconSettings, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PebbleIconSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PebbleIconSafeCracker = lv_img_create(ui_PageMenu);
    lv_img_set_src(ui_PebbleIconSafeCracker, &ui_img_gemini_generated_image_c210npc210npc210_png);
    lv_obj_set_width(ui_PebbleIconSafeCracker, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PebbleIconSafeCracker, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PebbleIconSafeCracker, 18);
    lv_obj_set_y(ui_PebbleIconSafeCracker, -32);
    lv_obj_set_align(ui_PebbleIconSafeCracker, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PebbleIconSafeCracker, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PebbleIconSafeCracker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_ScrollContainer = NULL;
    ui_Image2 = NULL;
    ui_PageMain = NULL;
    ui_Image1 = NULL;
    ui_CharacterImage = NULL;
    ui_NotificationIcon = NULL;
    ui_MainBatteryLabel = NULL;
    ui_WeatherIcon = NULL;
    ui_TimeLabel = NULL;
    ui_PageMenu = NULL;
    ui_PebbleIconQR = NULL;
    ui_PebbleIconPebbleSkip = NULL;
    ui_PebbleIconSettings = NULL;
    ui_PebbleIconSafeCracker = NULL;

}
