// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_ScrollContainer;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_PageMain;
extern lv_obj_t * ui_CharacterImage;
extern lv_obj_t * ui_NotificationIcon;
extern lv_obj_t * ui_MainBatteryLabel;
extern lv_obj_t * ui_WeatherIcon;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_PageMenu;
extern lv_obj_t * ui_PebbleIconQR;
extern lv_obj_t * ui_PebbleIconPebbleSkip;
extern lv_obj_t * ui_PebbleIconSettings;
extern lv_obj_t * ui_PebbleIconSafeCracker;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

