// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#include "ui.h"

lv_obj_t * uic_Image1;
lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_WeatherIcon = NULL;
lv_obj_t * ui_NotificationIcon = NULL;
lv_obj_t * ui_CharacterImage = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel1, 300);
    lv_obj_set_height(ui_Panel1, 300);
    lv_obj_set_x(ui_Panel1, 194);
    lv_obj_set_y(ui_Panel1, 269);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);

    ui_Image1 = ui_Image1_create(ui_Panel1);
    lv_img_set_src(ui_Image1, &ui_img_river_png);
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 0);

    ui_Image9 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_Image9, &ui_img_river_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, 9);
    lv_obj_set_y(ui_Image9, 19);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, -25);
    lv_obj_set_y(ui_TimeLabel, 70);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);

    ui_WeatherIcon = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_WeatherIcon, &ui_img_wether_png);
    lv_obj_set_width(ui_WeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherIcon, -50);
    lv_obj_set_y(ui_WeatherIcon, -19);
    lv_obj_set_align(ui_WeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WeatherIcon, 100);

    ui_NotificationIcon = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_NotificationIcon, &ui_img_notify_png);
    lv_obj_set_width(ui_NotificationIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NotificationIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NotificationIcon, 36);
    lv_obj_set_y(ui_NotificationIcon, -15);
    lv_obj_set_align(ui_NotificationIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NotificationIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NotificationIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_NotificationIcon, 25);

    ui_CharacterImage = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_CharacterImage, &ui_img_lucid_origin_a_cute_chibi_kingfisher_creature_as_a_digital_pet_0_png);
    lv_obj_set_width(ui_CharacterImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharacterImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharacterImage, 87);
    lv_obj_set_y(ui_CharacterImage, 50);
    lv_obj_set_align(ui_CharacterImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CharacterImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CharacterImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CharacterImage, 30);

    uic_Image1 = ui_Image1;

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Panel1 = NULL;
    uic_Image1 = NULL;
    ui_Image1 = NULL;
    ui_Image9 = NULL;
    ui_TimeLabel = NULL;
    ui_WeatherIcon = NULL;
    ui_NotificationIcon = NULL;
    ui_CharacterImage = NULL;

}
