// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_PebbleIconQR;
extern lv_obj_t * ui_PebbleIconGame;
extern lv_obj_t * ui_PebbleIconSettings;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

