// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_WeatherIcon;
extern lv_obj_t * ui_NotificationIcon;
extern lv_obj_t * ui_CharacterImage;
extern lv_obj_t * ui_MainBatteryLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Image1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

