// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#include "ui.h"

lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_PebbleIconQR = NULL;
lv_obj_t * ui_PebbleIconGame = NULL;
lv_obj_t * ui_PebbleIconSettings = NULL;
// event funtions

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_MenuScreen);
    lv_img_set_src(ui_Image10, &ui_img_river_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -4);
    lv_obj_set_y(ui_Image10, -58);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PebbleIconQR = lv_img_create(ui_MenuScreen);
    lv_img_set_src(ui_PebbleIconQR, &ui_img_qr_60_png);
    lv_obj_set_width(ui_PebbleIconQR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PebbleIconQR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PebbleIconQR, -70);
    lv_obj_set_y(ui_PebbleIconQR, -25);
    lv_obj_set_align(ui_PebbleIconQR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PebbleIconQR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PebbleIconQR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PebbleIconGame = lv_img_create(ui_MenuScreen);
    lv_img_set_src(ui_PebbleIconGame, &ui_img_setting_60_png);
    lv_obj_set_width(ui_PebbleIconGame, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PebbleIconGame, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PebbleIconGame, 18);
    lv_obj_set_y(ui_PebbleIconGame, -32);
    lv_obj_set_align(ui_PebbleIconGame, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PebbleIconGame, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PebbleIconGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PebbleIconSettings = lv_img_create(ui_MenuScreen);
    lv_img_set_src(ui_PebbleIconSettings, &ui_img_setting_60_png);
    lv_obj_set_width(ui_PebbleIconSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PebbleIconSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PebbleIconSettings, 19);
    lv_obj_set_y(ui_PebbleIconSettings, 51);
    lv_obj_set_align(ui_PebbleIconSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PebbleIconSettings, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PebbleIconSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    ui_MenuScreen = NULL;
    ui_Image10 = NULL;
    ui_PebbleIconQR = NULL;
    ui_PebbleIconGame = NULL;
    ui_PebbleIconSettings = NULL;

}
