// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#ifndef UI_QRSCREEN_H
#define UI_QRSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_QrScreen
extern void ui_QrScreen_screen_init(void);
extern void ui_QrScreen_screen_destroy(void);
extern lv_obj_t * ui_QrScreen;
extern lv_obj_t * ui_QrCode;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

