// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#include "ui.h"

lv_obj_t * ui_QrScreen = NULL;
lv_obj_t * ui_QrCode = NULL;
// event funtions

// build funtions

void ui_QrScreen_screen_init(void)
{
    ui_QrScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_QrScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_QrCode = lv_img_create(ui_QrScreen);
    lv_img_set_src(ui_QrCode, &ui_img_twitter_qr_png);
    lv_obj_set_width(ui_QrCode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_QrCode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_QrCode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QrCode, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_QrCode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_QrScreen_screen_destroy(void)
{
    if(ui_QrScreen) lv_obj_del(ui_QrScreen);

    // NULL screen variables
    ui_QrScreen = NULL;
    ui_QrCode = NULL;

}
