// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#ifndef UI_SKIPSCREEN_H
#define UI_SKIPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SkipScreen
extern void ui_SkipScreen_screen_init(void);
extern void ui_SkipScreen_screen_destroy(void);
extern lv_obj_t * ui_SkipScreen;
extern lv_obj_t * ui_SkipMessageLabel;
extern lv_obj_t * ui_SkipScoreLabel;
extern lv_obj_t * ui_SkipStoneImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

