// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#include "ui.h"

lv_obj_t * uic_SettingScreen;
lv_obj_t * ui_SettingScreen = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions

// build funtions

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_SettingScreen);
    lv_slider_set_value(ui_Slider1, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 108);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 49);
    lv_obj_set_y(ui_Slider1, -34);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -58);
    lv_obj_set_y(ui_Label1, -36);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Brightness");

    ui_Label2 = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -5);
    lv_obj_set_y(ui_Label2, 66);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Connection BLE / WiFi");

    ui_Label3 = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -32);
    lv_obj_set_y(ui_Label3, -71);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Vibration");

    ui_Switch1 = lv_switch_create(ui_SettingScreen);
    lv_obj_set_width(ui_Switch1, 42);
    lv_obj_set_height(ui_Switch1, 20);
    lv_obj_set_x(ui_Switch1, 42);
    lv_obj_set_y(ui_Switch1, -72);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);       /// States

    ui_Bar1 = lv_bar_create(ui_SettingScreen);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 99);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 51);
    lv_obj_set_y(ui_Bar1, -1);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -63);
    lv_obj_set_y(ui_Label4, 0);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Battery 100%");

    ui_Button1 = lv_btn_create(ui_SettingScreen);
    lv_obj_set_width(ui_Button1, 35);
    lv_obj_set_height(ui_Button1, 22);
    lv_obj_set_x(ui_Button1, 35);
    lv_obj_set_y(ui_Button1, 33);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -57);
    lv_obj_set_y(ui_Label5, 34);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "DeepSleep");

    ui_Panel2 = lv_obj_create(ui_SettingScreen);
    lv_obj_set_width(ui_Panel2, 237);
    lv_obj_set_height(ui_Panel2, 118);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 2);
    lv_obj_set_y(ui_Label7, -25);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Does it go into deep sleep\nwhen the battery is at 60%?");

    ui_Button2 = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Button2, 55);
    lv_obj_set_height(ui_Button2, 30);
    lv_obj_set_x(ui_Button2, -3);
    lv_obj_set_y(ui_Button2, 24);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "No");

    ui_Button3 = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Button3, 55);
    lv_obj_set_height(ui_Button3, 30);
    lv_obj_set_x(ui_Button3, -76);
    lv_obj_set_y(ui_Button3, 24);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Cancel");

    ui_Button4 = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Button4, 55);
    lv_obj_set_height(ui_Button4, 30);
    lv_obj_set_x(ui_Button4, 71);
    lv_obj_set_y(ui_Button4, 25);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Yes");

    uic_SettingScreen = ui_SettingScreen;

}

void ui_SettingScreen_screen_destroy(void)
{
    if(ui_SettingScreen) lv_obj_del(ui_SettingScreen);

    // NULL screen variables
    uic_SettingScreen = NULL;
    ui_SettingScreen = NULL;
    ui_Slider1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Switch1 = NULL;
    ui_Bar1 = NULL;
    ui_Label4 = NULL;
    ui_Button1 = NULL;
    ui_Label5 = NULL;
    ui_Panel2 = NULL;
    ui_Label7 = NULL;
    ui_Button2 = NULL;
    ui_Label6 = NULL;
    ui_Button3 = NULL;
    ui_Label8 = NULL;
    ui_Button4 = NULL;
    ui_Label9 = NULL;

}
