// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Checkbox2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Image1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

