// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-pebble-gui

#include "ui.h"

lv_obj_t * ui_SkipScreen = NULL;
lv_obj_t * ui_SkipMessageLabel = NULL;
lv_obj_t * ui_SkipScoreLabel = NULL;
lv_obj_t * ui_SkipStoneImage = NULL;
// event funtions

// build funtions

void ui_SkipScreen_screen_init(void)
{
    ui_SkipScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SkipScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SkipMessageLabel = lv_label_create(ui_SkipScreen);
    lv_obj_set_width(ui_SkipMessageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SkipMessageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SkipMessageLabel, -53);
    lv_obj_set_y(ui_SkipMessageLabel, -52);
    lv_obj_set_align(ui_SkipMessageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SkipMessageLabel, "SWING ME!");

    ui_SkipScoreLabel = lv_label_create(ui_SkipScreen);
    lv_obj_set_width(ui_SkipScoreLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SkipScoreLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SkipScoreLabel, -23);
    lv_obj_set_y(ui_SkipScoreLabel, 22);
    lv_obj_set_align(ui_SkipScoreLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SkipScoreLabel, "0 SKIPS");

    ui_SkipStoneImage = lv_img_create(ui_SkipScreen);
    lv_img_set_src(ui_SkipStoneImage, &ui_img_qr3_png);
    lv_obj_set_width(ui_SkipStoneImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SkipStoneImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SkipStoneImage, -1);
    lv_obj_set_y(ui_SkipStoneImage, -40);
    lv_obj_set_align(ui_SkipStoneImage, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SkipStoneImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SkipStoneImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_SkipScreen_screen_destroy(void)
{
    if(ui_SkipScreen) lv_obj_del(ui_SkipScreen);

    // NULL screen variables
    ui_SkipScreen = NULL;
    ui_SkipMessageLabel = NULL;
    ui_SkipScoreLabel = NULL;
    ui_SkipStoneImage = NULL;

}
